### ISSUE TITLE
CLI Timeout exception

### ISSUE THREAD

**Issue by NevynUK** [WildernessLabs/Meadow.CLI#143]
I'm using the CLI with VS Code and I get the following exception when detaching VS Code from the debugger:

```
Unhandled exception. Error receiving data from Visual Studio
System.AggregateException: One or more errors occurred. (Timeout while writing to serial port)
 ---> System.TimeoutException: Timeout while writing to serial port
   at Meadow.CLI.Core.Devices.MeadowLocalDevice.<>c.<EncodeAndSendPacket>b__57_0() in D:\a\Meadow.CLI\Meadow.CLI\main\Meadow.CLI.Core\Devices\MeadowLocalDeviceComms.cs:line 277
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.<>c.<.cctor>b__56_0(Object obj)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
[1]    34182 abort      meadow debug
```

Steps to reproduce:
* Create a Meadow application and deploy to the board
* Set a breakpoint
* Execute `meadow debug` from a command line
* Start VS Code, open the source code folder and start debugging the application
* Run to the breakpoint.
* Hit detach / end debugging in VS Code
* Wait

The CLI should generate the above exception.

FYI - `launch.json` I'm using looks like this:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach",
            "type": "mono",
            "request": "attach",
            "address": "127.0.0.1",
            "port": 4024
        }
    ]
}
```

**Comment by adrianstevens** [comment]
legacy - closing issue
